### ISSUE TITLE
authenticationUrl and server_identifier can not be updated

### ISSUE THREAD

**Issue by cornelinux** [SURFnet/tiqr-client-android#14]
I am adding TiQR to a service of mine.
During playing around with adding an account to the app - removing it - adding the account again...

I realized the following:

I added an account with a certain

* authenticationUrl and
* server{identidifier}

I deleted the account, played around with my code, tested and added the account to the App again (same account (userId)) and I realized, that the new account would not use a new authenticationURl and server_identifier.

Only after deleting the App-Data in the Smartphone Application settings I was able to add the account with the new authenticationUrl and server_identifier.

I am using version 2.4 
https://play.google.com/store/apps/details?id=org.tiqr.authenticator

**Comment by petercv** [comment]
Thanks for the report. We will look into it!

**Comment by ijansch** [comment]
This is fixed in pull request #22. @cornelinux let us know if meets your needs!
