### ISSUE TITLE
Difficulties scanning QR: ratio between screen/ scan box does not suit larger devices

### ISSUE THREAD

**Issue by eefjevanderharst** [SURFnet/tiqr-client-android#18]
The ratio between the total device screen and the available 'scan box' which makes it difficult to scan a QR code. 

In iOS the scan box is almost as large as my device screen, but in Android I only see a small scan box, this makes it more difficult to scan, especially when you hold your phone close.

Solution: Change the size of the scan box to be larger on larger phones/ tablets 

See attached screenshots.
![screenshot qr](https://cloud.githubusercontent.com/assets/8789958/10647492/fd7bf972-7838-11e5-9687-4097dc7f84eb.png)
![screenshot qr ios](https://cloud.githubusercontent.com/assets/8789958/10647498/0433d762-7839-11e5-8ef7-ecb75e8f96d9.PNG)

**Comment by joostd** [comment]
fixed in latest commit
