### ISSUE TITLE
Unknown identity error message with certain user identifiers

### ISSUE THREAD

**Issue by joostd** [SURFnet/tiqr-client-android#24]
When invoking stepup authentication, the Android tiqr client will display the message "Unknown identity for service, please enrol first." (`error_auth_unknown_identity`) if the user has enrolled with an identifier that contains a `@` sign. 

The `@` sign is escaped in the authentication URL, e.g.  
`tiqrauth://jodi%40surfnet.nl@demo.tiqr.org/b479b324a7a57298d8048d5a004f2984/2b277e9b41/demo.tiqr.org`, but is not recognised as a valid user identifier.

Note that identifiers with an `@` sign are quite common in stepup scenarios.

**Comment by andrei-egeniq** [comment]
Are all URLs encoded? The enrolment metadata.php Json "identifier" field as well?

**Comment by joostd** [comment]
See for instance:
https://demo.tiqr.org/v3/secured.php

The enrolment QR decodes into tiqrenroll://https//demo.tiqr.org/simplesaml/module.php/authTiqr/metadata.php?key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Serverside, a user is provisioned similar to:
{"userId":"john@example.org","displayName":"John Doe"}
