### ISSUE TITLE
tiqr uses a hardcoded and obsolete token exchange url

### ISSUE THREAD

**Issue by joostd** [SURFnet/tiqr-client-android#30]
See https://github.com/SURFnet/tiqr-client-android/blob/master/shared/src/main/java/org/tiqr/service/notification/NotificationService.java#L21
where the (obsolete) token exchange URL of https://mobi.surfnet.nl/tokenexchange is used.

Moreover, this URL should not be hardcoded here.

This explains various problems with push notifications.

**Comment by joostd** [comment]
Could you move the URL to a configuration file?

**Comment by dzolnai** [comment]
We could make it a string in the build.gradle file, if that's ok

**Comment by joostd** [comment]
sounds good to me!

**Comment by dzolnai** [comment]
Fixed with #32
