### ISSUE TITLE
Change obsolete SURFnet logo in push notification

### ISSUE THREAD

**Issue by eefjevanderharst** [SURFnet/tiqr-client-android#34]
The Tiqr push notification shows an obsolete SURFnet logo, please change this in a tiqr logo (like in current iOS app) See screenshots.
![img_1866](https://cloud.githubusercontent.com/assets/8789958/19965224/46ac2af6-a1c6-11e6-8b00-2908975367a0.jpeg)
![img_1867](https://cloud.githubusercontent.com/assets/8789958/19965223/46abec94-a1c6-11e6-9ed7-ed0cad007463.png)
![img_1865](https://cloud.githubusercontent.com/assets/8789958/19965225/46ac40c2-a1c6-11e6-82f9-822d443c9e6c.jpeg)

Tested with Galaxy S4, Android 5.0.1

**Comment by dzolnai** [comment]
Thank you for the report, fixed with #35 :)
