### ISSUE TITLE
include tiqr client version in user agent header

### ISSUE THREAD

**Issue by joostd** [SURFnet/tiqr-client-android#49]
The User Agent header sent when the tiqr client communicates with the tiqr server currently does not contain the tiqr version. For instance, a Samsung Galaxy S8 sends a user agent header similar to:

    Dalvik/2.1.0 (Linux; U; Android 8.0.0; SM-G950F Build/R16NW)

This information is very useful, but please also include the tiqr client version in the user agent header similar to the way this is done in the iOS version of tiqr. For instance:

    tiqr/2.5.7 CFNetwork/975.0.3 Darwin/18.2.0

**Comment by okaymak** [comment]
Fixed in [refactoring branch](https://github.com/SURFnet/tiqr-client-android/blob/feature/refactor/data/src/main/java/org/tiqr/data/api/interceptor/UserAgentInjector.kt)
