### ISSUE TITLE
Validate notificationToken received from tokenexchange

### ISSUE THREAD

**Issue by phavekes** [SURFnet/tiqr-client-android#83]
It seems that any response (even an error) from the tokenexchange wil be used as new notificationtoken, and stored in the prefs. 

Should the http-response be checked before processing the response?

https://github.com/SURFnet/tiqr-client-android/blob/009fec232e56510bbcb39f86c291d0389076c049/shared/src/main/java/org/tiqr/service/notification/NotificationService.kt#L43

**Comment by dzolnai** [comment]
Keeping this issue open for visibility until it has been released to the Play Store.
