### ISSUE TITLE
Unable to input pin with auto-fill service

### ISSUE THREAD

**Issue by sanderboele** [SURFnet/tiqr-client-android#96]
It's not possible to create a pin when an auto-fill service is enabled on Android 10. 

Steps to reproduce:

1) install Bitwarden and enable the Bitwarden auto-fill service (Languages & Input -> Auto-fill service)
2) create a new tiqr token and try to input a pin
3) bitwarden auto-filler is activated which prevents pin input. 

I can temporarily disable the auto-fill service to work around this problem, but I reckon most users wouldn't be able to do that. I've heard of users having the same problem with keypass.

**Comment by joostd** [comment]
Thanks for your issue report!
We are aware of conflicts with password managers in general. We are working on a fix.

We have a public beta release available [here](https://play.google.com/apps/testing/org.tiqr.authenticator) that should work well with apps interfering with password/PIN entry.

We haven't checked with BitWarden though, so if you are willing to test, please do!
(if you have an important tiqr account on your phone, please make a backup first)
